### PR TITLE
Fix/battery

### LINKED ISSUE #1715: Battery segment returns error when running Ubuntu in WSL
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

The battery segment returns an error when running Ubuntu (Ubuntu 20.04.3 LTS) in WSL. 

The error message is "[{Current:open /sys/class/power_supply/battery/charge_now: no such file or directory Full:open /sys/class/power_supply/battery/charge_full: no such file or directory Design:open /sys/class/power_supply/battery/charge_full_design: no such file or directory}]"

Is this a known limitation or am I just doing something wrong?

### Theme

I am running a custom theme with the battery segment looking like this:
image

This result in this prompt (execution time segment can be ignored), with the red symbol being \uf590:
image

If printing the error message instead of the symbol I get this:
image

The config works as expected running in Powershell, looking like this:
image

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

bash

### Log output

```shell
Version: 7.11.0

Segments:

ConsoleTitle(false)  -   0 ms -
os(true)             -   5 ms - wsl: 
shell(true)          -   4 ms - uni
az(false)            -   0 ms -
git(false)           -   0 ms -
time(true)           -   1 ms - | 23:34
path(true)           -  19 ms - | ~
executiontime(true)  -   1 ms - 0ms |
battery(true)        -   6 ms -  
text(true)           -   1 ms - $

Run duration: 42.7949ms

Cache path: /home/linus/.cache/oh-my-posh

Logs:

2022/02/06 23:34:33 Args duration: 13.5µs, args:
2022/02/06 23:34:33 Args duration: 3.2µs, args:
2022/02/06 23:34:33 Args duration: 4.3µs, args:
2022/02/06 23:34:33 Shell duration: 6.8µs, args:
2022/02/06 23:34:33 debug: Getenv

2022/02/06 23:34:33 Getenv duration: 49µs, args: OMP_CACHE_DISABLED
2022/02/06 23:34:33 debug: Pwd
/home/linus
2022/02/06 23:34:33 Pwd duration: 205.9µs, args:
2022/02/06 23:34:33 PathSeperator duration: 2.5µs, args:
2022/02/06 23:34:33 PathSeperator duration: 2.3µs, args:
2022/02/06 23:34:33 debug: Pwd
/home/linus
2022/02/06 23:34:33 Pwd duration: 16.3µs, args:
2022/02/06 23:34:33 GOOS duration: 2.7µs, args:
2022/02/06 23:34:33 Root duration: 8µs, args:
2022/02/06 23:34:33 Shell duration: 2.9µs, args:
2022/02/06 23:34:33 ErrorCode duration: 2.5µs, args:
2022/02/06 23:34:33 debug: Getenv
Ubuntu
2022/02/06 23:34:33 Getenv duration: 35.4µs, args: WSL_DISTRO_NAME
2022/02/06 23:34:33 IsWsl duration: 100.5µs, args:
2022/02/06 23:34:33 debug: Pwd
/home/linus
2022/02/06 23:34:33 Pwd duration: 14.6µs, args:
2022/02/06 23:34:33 PathSeperator duration: 3.1µs, args:
2022/02/06 23:34:33 PathSeperator duration: 3.9µs, args:
2022/02/06 23:34:33 User duration: 7.4µs, args:
2022/02/06 23:34:33 Host duration: 12.4µs, args:
2022/02/06 23:34:33 GOOS duration: 2.6µs, args:
2022/02/06 23:34:33 TemplateCache duration: 852µs, args:
2022/02/06 23:34:33 TemplateCache duration: 2.7µs, args:
2022/02/06 23:34:33 debug: Pwd
/home/linus
2022/02/06 23:34:33 Pwd duration: 25.9µs, args:
2022/02/06 23:34:33 Shell duration: 2.7µs, args:
2022/02/06 23:34:33 TemplateCache duration: 2.6µs, args:
2022/02/06 23:34:33 TemplateCache duration: 3.6µs, args:
2022/02/06 23:34:33 TemplateCache duration: 2.8µs, args:
2022/02/06 23:34:33 TemplateCache duration: 2.7µs, args:
2022/02/06 23:34:33 debug: Pwd
/home/linus
2022/02/06 23:34:33 Pwd duration: 12.9µs, args:
2022/02/06 23:34:33 error: FileContent
open /home/linus/.azure/azureProfile.json: no such file or directory
2022/02/06 23:34:33 FileContent duration: 208.8µs, args: /home/linus/.azure/azureProfile.json
2022/02/06 23:34:33 error: FileContent
open /home/linus/.azure/AzureRmContext.json: no such file or directory
2022/02/06 23:34:33 FileContent duration: 131.5µs, args: /home/linus/.azure/AzureRmContext.json
2022/02/06 23:34:33 error: FileContent
open /home/linus/.Azure/AzureRmContext.json: no such file or directory
2022/02/06 23:34:33 FileContent duration: 100.9µs, args: /home/linus/.Azure/AzureRmContext.json
2022/02/06 23:34:33 debug: Pwd
/home/linus
2022/02/06 23:34:33 Pwd duration: 11.5µs, args:
2022/02/06 23:34:33 debug: Getenv
Ubuntu
2022/02/06 23:34:33 Getenv duration: 10.2µs, args: WSL_DISTRO_NAME
2022/02/06 23:34:33 IsWsl duration: 26.6µs, args:
2022/02/06 23:34:33 debug: Pwd
/home/linus
2022/02/06 23:34:33 Pwd duration: 9.6µs, args:
2022/02/06 23:34:33 GOOS duration: 2.2µs, args:
2022/02/06 23:34:33 HasCommand duration: 320.7µs, args: git
2022/02/06 23:34:33 debug: Pwd
/home/linus
2022/02/06 23:34:33 Pwd duration: 9.6µs, args:
2022/02/06 23:34:33 error: HasParentFilePath
stat /.git: no such file or directory
2022/02/06 23:34:33 HasParentFilePath duration: 436.6µs, args: .git
2022/02/06 23:34:33 debug: Pwd
/home/linus
2022/02/06 23:34:33 Pwd duration: 8.2µs, args:
2022/02/06 23:34:33 TemplateCache duration: 2.9µs, args:
2022/02/06 23:34:33 debug: Pwd
/home/linus
2022/02/06 23:34:33 Pwd duration: 8.5µs, args:
2022/02/06 23:34:33 debug: Pwd
/home/linus
2022/02/06 23:34:33 Pwd duration: 33.6µs, args:
2022/02/06 23:34:33 Args duration: 2.3µs, args:
2022/02/06 23:34:33 debug: Pwd
/home/linus
2022/02/06 23:34:33 Pwd duration: 26.4µs, args:
2022/02/06 23:34:33 GOOS duration: 1.5µs, args:
2022/02/06 23:34:33 GOOS duration: 1.4µs, args:
2022/02/06 23:34:33 PathSeperator duration: 2.5µs, args:
2022/02/06 23:34:33 Args duration: 2.8µs, args:
2022/02/06 23:34:33 debug: Pwd
/home/linus
2022/02/06 23:34:33 Pwd duration: 12.5µs, args:
2022/02/06 23:34:33 GOOS duration: 1.5µs, args:
2022/02/06 23:34:33 GOOS duration: 1.8µs, args:
2022/02/06 23:34:33 PathSeperator duration: 2.9µs, args:
2022/02/06 23:34:33 GOOS duration: 1.6µs, args:
2022/02/06 23:34:33 debug: Getenv
Ubuntu
2022/02/06 23:34:33 Getenv duration: 15.5µs, args: WSL_DISTRO_NAME
2022/02/06 23:34:33 IsWsl duration: 32.6µs, args:
2022/02/06 23:34:33 debug: RunCommand
//wsl$/Ubuntu/home/linus
2022/02/06 23:34:33 RunCommand duration: 13.4558ms, args: wslpath -m /home/linus
2022/02/06 23:34:33 StackCount duration: 3.2µs, args:
2022/02/06 23:34:33 TemplateCache duration: 3.7µs, args:
2022/02/06 23:34:33 TemplateCache duration: 3.4µs, args:
2022/02/06 23:34:33 TemplateCache duration: 3.3µs, args:
2022/02/06 23:34:33 TemplateCache duration: 3.2µs, args:
2022/02/06 23:34:33 debug: Pwd
/home/linus
2022/02/06 23:34:33 Pwd duration: 15.8µs, args:
2022/02/06 23:34:33 ExecutionTime duration: 2.9µs, args:
2022/02/06 23:34:33 TemplateCache duration: 3.2µs, args:
2022/02/06 23:34:33 debug: Pwd
/home/linus
2022/02/06 23:34:33 Pwd duration: 14.7µs, args:
2022/02/06 23:34:33 error: BatteryInfo
[{Current:open /sys/class/power_supply/battery/charge_now: no such file or directory Full:open /sys/class/power_supply/battery/charge_full: no such file or directory Design:open /sys/class/power_supply/battery/charge_full_design: no such file or directory}]
2022/02/06 23:34:33 BatteryInfo duration: 4.8925ms, args:
2022/02/06 23:34:33 TemplateCache duration: 8.7µs, args:
2022/02/06 23:34:33 TemplateCache duration: 7.2µs, args:
2022/02/06 23:34:33 debug: Pwd
/home/linus
2022/02/06 23:34:33 Pwd duration: 13.1µs, args:
2022/02/06 23:34:33 TemplateCache duration: 2.6µs, args:
2022/02/06 23:34:33 debug: Getenv

2022/02/06 23:34:33 Getenv duration: 21.9µs, args: XDG_CACHE_HOME
2022/02/06 23:34:33 CachePath duration: 215.2µs, args:
```

### PR DESCRIPTION
**Pull request by lnu**
### Prerequisites

- [x] I have read and understood the `CONTRIBUTING` guide
- [x] The commit message follows the [conventional commits][cc] guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes/features)

### Description

Enable only in WSL2, disable in WSL

Fix #1715 

[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

File: src/segments/battery.go [hunk 1]
```diff
@@ -32,6 +32,10 @@ func (b *Battery) Template() string {
 }
 
 func (b *Battery) Enabled() bool {
+	if !b.env.IsWsl2() {
```
Comment (JanDeDobbeleer) [inline src/segments/battery.go:35]: Don't we need to validate for WSL first? As this could ruin standard linux/macos functionality?

Comment (lnu) [reply src/segments/battery.go:35]: isWsl2 implicitly calls isWsl first
