### PR TITLE
fix(fonts): register user fonts correctly on Windows

### LINKED ISSUE #4169: Can't find fonts after user installation
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

When installing a font on Windows 11 with `oh-my-posh font install --user`, I cannot find the font in the Personalization > Fonts page nor select it in apps.

I believe this is a registry issue.
When installing with double click, the registry has:
```reg
[HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\Fonts]
"Agave Nerd Font Regular (TrueType)"="C:\\Users\\dan\\AppData\\Local\\Microsoft\\Windows\\Fonts\\AgaveNerdFont-Regular.ttf"
```

When installing with oh-my-posh, the registry has:
```reg
[HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\Fonts]
"Agave Nerd Font Regular (TrueType)"="AgaveNerdFont-Regular.ttf"
```

### Theme

available upon request

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
available upon request
```

### PR DESCRIPTION
**Pull request by rotu**
### Prerequisites

- [x] I have read and understood the [contributing guide][CONTRIBUTING.md].
- [x] The commit message follows the [conventional commits][cc] guidelines.
- [ ] Tests for the changes have been added (for bug fixes / features).
- [ ] Docs have been added/updated (for bug fixes / features).

### Description

Fix #4169

### <samp>🤖 Generated by Copilot at 84298e3</samp>

Fix font installation bug for non-admin Windows users. Use different registry values for `src/font/install_windows.go` based on user privileges.

### <samp>🤖 Generated by Copilot at 84298e3</samp>

* Fix font installation for non-admin users on Windows by using different registry values based on user privileges ([link](https://github.com/JanDeDobbeleer/oh-my-posh/pull/4170/files?diff=unified&w=0#diff-0fb1cd433036960283343e1a07e4b3ebe00f5a5271e426899f5d305d91aa43daL45-R51))
* Use consistent font name for registry value in both cases ([link](https://github.com/JanDeDobbeleer/oh-my-posh/pull/4170/files?diff=unified&w=0#diff-0fb1cd433036960283343e1a07e4b3ebe00f5a5271e426899f5d305d91aa43daL62-R66))

[CONTRIBUTING.md]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md
[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

File: src/font/install_windows.go [hunk 1]
```diff
@@ -42,9 +42,14 @@ func install(font *Font, admin bool) error {
 	}
 
 	// Add registry entry
-	reg := registry.LOCAL_MACHINE
-	if !admin {
+	var reg registry.Key
```
Comment (JanDeDobbeleer) [inline src/font/install_windows.go]: I would instantiate these as admin, then change the values when you're not admin. Assuming admin is the most common option. That way the if/else isn't necessary. I try to avoid if/else at all times.

Comment (rotu) [reply src/font/install_windows.go]: Thanks! I've never go'ed (gone?) before :-)

**Comment by rotu** [comment]
I'm not sure about this comment:

https://github.com/JanDeDobbeleer/oh-my-posh/blob/2d2af929a9c0b9a0459d24cdcdc835b019ac5f75/website/docs/installation/fonts.mdx#L30-L34

Are those "side-effects" just due to this registry issue (and the notice can be removed) or is there more to investigate?

**Comment by rotu** [comment]
I've confirmed locally that this fixes the issue (I can install a font and then select it in Windows Terminal). I'm not intending to write Windows integration tests.

**Comment by JanDeDobbeleer** [comment]
@rotu no tests needed for this, it either works or doesn't. There used to be issues when installing the font as user on certain Windows systems where they weren't picked up by other applications. Not by installing via oh-my-posh, but rather from double clicking the font to install. It predates the font installation in oh-my-posh.

**Review by JanDeDobbeleer — APPROVED** [review]

**Comment by JanDeDobbeleer** [comment]
@all-contributors please add @rotu for code

This is pure magic 🪄! @holopin-bot @rotu wizard
