### PR TITLE
fix: correct hyperlinks for Git Bash

### LINKED ISSUE #17602: "duplicate tab" fails due to improper path being sent.
### Windows Terminal version

1.20.11781.0

### Windows build number

Microsoft Windows [Version 10.0.26100.1150]

### Other Software

Git bash
Oh-My-Posh

### Steps to reproduce

1. Open up a git bash window
2. <kbd>ctrl-shift-P</kbd>
3. "duplicate tab"

### Expected Behavior

open to current directory

### Actual Behavior

```
[error 2147942667 (0x8007010b) when launching `C:/Program Files/Git/bin/bash.exe -i -l']
Could not access starting directory "C:\Users13:06:36rajano"
```

```
[error 2147942667 (0x8007010b) when launching `C:/Program Files/Git/bin/bash.exe -i -l']
Could not access starting directory "C:\WINDOWS\system32\Tue Jul 23h\iblum-stack"
```

### PR DESCRIPTION
**Pull request by JanDeDobbeleer**
### Prerequisites

- [x] I have read and understood the [contributing guide][CONTRIBUTING.md].
- [x] The commit message follows the [conventional commits][cc] guidelines.
- [x] Tests for the changes have been added (for bug fixes / features).
- [x] Docs have been added/updated (for bug fixes / features).

resolves https://github.com/microsoft/terminal/issues/17602

[CONTRIBUTING.md]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md
[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by JanDeDobbeleer** [comment]
I'm fixing the tests but first I need to go and eat an ice cream. I promised the misses.

File: src/terminal/writer.go [hunk 1]
```diff
@@ -163,9 +163,11 @@ func Pwd(pwdType, userName, hostName, pwd string) string {
 	}
 
 	if strings.HasSuffix(pwd, ":") {
-		pwd += "\\"
+		pwd += `/`
 	}
 
+	pwd = strings.ReplaceAll(pwd, `\`, `/`)
```
Comment (lewis-yeung) [inline src/terminal/writer.go:169]: @JanDeDobbeleer On Linux/macOS, the backslash (`\`) is a valid character in filenames. In that case it will produce a wrong path. The same to a colon character (`:`).

Comment (JanDeDobbeleer) [reply src/terminal/writer.go:169]: @lewis-yeung I'll adjust this for cygwin alone.
